### ISSUE TITLE
Graphical suggestion on teacher's stats page

### ISSUE THREAD

**Issue by AlbertoPisanello** [Thefolle/PULSeBS_Repo#14]
I suggest you to move the word on the left of the graph (Lecture, month..) , on the top of the y axes.
This could increase the clearness of the page.

**Comment by Thefolle** [comment]
We found another solution for this w.r.t. the proposed one, because the library used to render the graph is not flexible enough to support your solution. The axis label is now more distant from the axis itself, so clearness has been improved in any case.
